[package]
name = "day-9"
version = "0.1.0"
authors = ["Vlad Stepanov <8uk.8ak@gmail.com>"]
edition = "2018"

[dependencies]
advent-utils = { git = "https://github.com/utter-step/advent-utils" }

intrusive-collections = "0.8"

serde = { version = "1", features = ["derive"] }
