[package]
name = "day-11"
version = "0.1.0"
authors = ["Vlad Stepanov <8uk.8ak@gmail.com>"]
edition = "2018"

[dependencies]
advent-utils = { git = "https://github.com/utter-step/advent-utils" }

serde = { version = "1", features = ["derive"] }
