[package]
name = "day-10"
version = "0.1.0"
authors = ["Vlad Stepanov <8uk.8ak@gmail.com>"]
edition = "2018"

[dependencies]
advent-utils = { path = "../advent-utils" }

lazy_static = "1.2.0"
regex = "1"

serde = "1"
serde_derive = "1"
