[package]
name = "day-10"
version = "0.1.0"
authors = ["Vlad Stepanov <8uk.8ak@gmail.com>"]
edition = "2018"

[dependencies]
advent-utils = { git = "https://github.com/utter-step/advent-utils" }

lazy_static = "1.2.0"
regex = "1"

serde = { version = "1", features = ["derive"] }
